<?php
	use Contract\Form\Kontrak\PembuatanForm;
	use Contract\Form\Kontrak\KontrakFieldset;
	use Contract\Form\Kontrak\KomentarFieldset;
	use Contract\Form\Kontrak\DokumenFieldset;
	use Zend\Form\Element\Select;
	use Zend\Form\Element\Text;
	use Zend\Form\Element\File;
	use Zend\Form\Element\Checkbox;
	use Zend\Form\Element\Collection;
	use Contract\Entity\Kontrak\Komentar;
	
	$this->headTitle($this->pageTitle);
	
	/* @var $form Contract\Form\Kontrak\PembuatanForm */
	$form = $this->form;
	
	/* @var $tender Procurement\Entity\Tender\Tender */
	$tender = $this->tender;
	
	/* @var $kontrak Contract\Entity\Kontrak\Kontrak */
	$kontrak = $this->kontrak;
?>
<script type="text/javascript">
<!--
$(function(){
	$.datepicker.setDefaults($.datepicker.regional['in_ID']);
	$('.datepicker').datepicker();
	$('.datepicker').datepicker({
		changeYear: true,
		changeMonth: true,
		yearRange: '1999:2030',
		format: "dd-mm-yy"
	});

	$('#addMilestone').click(function() {
		alert('Add Milestone');
	});
	$('#editMilestone').click(function() {
		alert('Edit Milestone');
	});
	$('#deleteMilestone').click(function() {
		$.facebox('Delete Milestone');
	});
});
//-->
</script>
<div id="right">
	<?php 
		$form->prepare();
		echo $this->form()->openTag($form);
		
	?>
	<div class="section">
		<!-- Start Contract Header -->
		<div class="box">
			<div class="title">
				HEADER
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;">Nomor Pengadaan</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Pengguna Barang / Jasa</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Vendor</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tipe Kontrak</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tanggal Penetapan Pemenang</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Jenis Kontrak</td>
						<td>
							<div>
								<!-- Select Jenis Kontrak, SPK atau Perjanjian -->
								<?php echo $this->formSelect($form->get(KontrakFieldset::DEFAULT_NAME)->get('jenisKontrak')) ?>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;"><?php echo $form->get(KontrakFieldset::DEFAULT_NAME)->get('tanggalMulaiKontrak')->getOption('label')?></td>
						<td>
							<div>
								<!-- Datepicker tanggal mulai kontrak -->
								<?php echo $this->formInput($form->get(KontrakFieldset::DEFAULT_NAME)->get('tanggalMulaiKontrak'))?>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;"><?php echo $form->get(KontrakFieldset::DEFAULT_NAME)->get('tanggalAkhirKontrak')->getOption('label')?></td>
						<td>
							<div>
								<!-- Datepicker tanggal berakhir kontrak -->
								<?php echo $this->formInput($form->get(KontrakFieldset::DEFAULT_NAME)->get('tanggalAkhirKontrak'))?>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Nilai HPS</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Nilai Kontrak</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;"><?php echo $form->get(KontrakFieldset::DEFAULT_NAME)->get('judulPekerjaan')->getOption('label')?></td>
						<td>
							<div>
								<!-- Textfield judul pekerjaan -->
								<?php echo $this->formInput($form->get(KontrakFieldset::DEFAULT_NAME)->get('judulPekerjaan'))?>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;"><?php echo $form->get(KontrakFieldset::DEFAULT_NAME)->get('deskripsiPekerjaan')->getOption('label')?></td>
						<td>
							<div>
								<!-- Textarea deksripsi pekerjaan -->
								<?php echo $this->formTextarea($form->get(KontrakFieldset::DEFAULT_NAME)->get('deskripsiPekerjaan'))?>
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<!-- End Contract Header -->
		<!-- Start Contract Item -->
		<div class="box">
			<div class="title">
				ITEM
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1" id="contractItem">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 150px;">Kode Barang / Jasa</th>
							<th>Deskripsi</th>
							<th style="width: 200px;">Harga Satuan</th>
							<th style="width: 100px;">Satuan</th>
							<th style="width: 100px;">Jumlah</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Contract Item -->
		<!-- Start Contract Milestone -->
		<div class="box">
			<div class="title">
				MILESTONE
				<span class="hide"></span>
			</div>
			<div class="content">
				<div class="uibutton-toolbar">
					<button type="button" id="addMilestone" class="uibutton">Tambah Milestone</button>
				</div>
				<table class="style1" id="contractMilestone">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th>Deskripsi</th>
							<th style="width: 200px;">Tanggal Target</th>
							<th style="width: 100px;">Bobot</th>
							<th style="width: 125px;"></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center;"></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><input type="button" id="editMilestone" class="uibutton" value="Ubah" /><input type="button" id="deleteMilestone" class="uibutton" value="Hapus" /></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Contract Milestone -->
		<!-- Start Contract Lampiran -->
		<?php 
			/* @var $documentFieldsetCollection Collection */
			$documentFieldsetCollection = $form->get(KontrakFieldset::DEFAULT_NAME)->get(DokumenFieldset::DEFAULT_COLLECTION_NAME);
		?>
		<div class="box">
			<div class="title">
				LAMPIRAN
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1" id="contractAttachment">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 250px;">Kategori</th>
							<th style="width: 300px;">Deskripsi Lampiran</th>
							<th>File</th>
							<th style="width: 75px;">Kirim Ke Vendor</th>
						</tr>
					</thead>
					<tbody>
					<?php 
						foreach ($documentFieldsetCollection->getIterator() as $documentFieldset) : 
					?>
						<tr>
							<td style="text-align: center;"><?php echo $index += 1?></td>
							<td><?php echo $this->formSelect($documentFieldset->get('kodeKategori'))?></td>
							<td><?php echo $this->formText($documentFieldset->get('keterangan'))?></td>
							<td><?php echo $this->formFile($documentFieldset->get('namaFile'))?></td>
							<td style="text-align: center;"><?php echo $this->formCheckbox($documentFieldset->get('statusPublish'))?></td>
						</tr>
					<?php 
						endforeach; 
					?>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Contract Lampiran -->
		<!-- Start Contract Comment -->
		<?php 
			/* @var $komentarFieldsetCollection Collection */
			$komentarFieldsetCollection = $form->get(KontrakFieldset::DEFAULT_NAME)->get(KomentarFieldset::DEFAULT_COLLECTION_NAME);
			$komentarFieldsetTemplate = $komentarFieldsetCollection->getTemplateElement();
			foreach ($komentarFieldsetTemplate->getIterator() as $element) {
				$element->setName(str_replace($komentarFieldsetCollection->getTemplatePlaceholder(), $komentarFieldsetCollection->getCount(), $element->getName()));
			}
		?>
		<div class="box">
			<div class="title">
				KOMENTAR
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;"><?php echo $komentarFieldsetTemplate->get('isi')->getOption('label')?></td>
						<td>
							<div>
								<!-- Textarea komentar -->
								<?php echo $this->formTextarea($komentarFieldsetTemplate->get('isi')) ?>
								
							</div>
						</td>
					</tr>
				</table>
				
				<?php if($komentarFieldsetCollection->getCount() > 0) : ?>
				<table class="style1" id="contractComments">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 200px;">Nama</th>
							<th style="width: 200px;">Tanggal</th>
							<th>Komentar</th>
						</tr>
					</thead>
					<tbody>
					<?php foreach ($komentarFieldsetCollection->getObject() as $komentar) : /* @var $komentar Komentar */ ?>
						<tr>
							<td><?php echo $indexKomentar += 1?></td>
							<td><?php ?></td>
							<td><?php echo $komentar->getIsi()?></td>
							<td><?php echo $komentar->getTanggal()->format('d M Y') ?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
				<?php endif; ?>
			</div>
		</div>
		<!-- End Contract Comment -->
		
		<!-- Start Button Container -->
		<div class="box">
			<div class="uibutton-toolbar">
				<?php echo $this->formHidden($form->get('security')) ?>
				<?php echo $this->formElement($form->get('submitDraft'))?>
				<?php echo $this->formElement($form->get('submit'))?>
				<a href="<?php echo $this->url('contract/todo')?>" class="uibutton">Kembali</a>
			</div>
		</div>
		<!-- End Button Container -->
	</div>
	<?php 
		echo $this->form()->closeTag();
	?>
</div>