<div id="right">
	<div class="section">
		<!-- Start Contract Header -->
		<div class="box">
			<div class="title">
				HEADER
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;">Nomor Pengadaan</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Pengguna Barang / Jasa</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Vendor</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tipe Kontrak</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tanggal Penetapan Pemenang</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Jenis Kontrak</td>
						<td>
							<div>
								<!-- Select Jenis Kontrak, SPK atau Perjanjian -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tanggal Mulai Kontrak</td>
						<td>
							<div>
								<!-- Datepicker tanggal mulai kontrak -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tanggal Berakhir Kontrak</td>
						<td>
							<div>
								<!-- Datepicker tanggal berakhir kontrak -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Nilai HPS</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Nilai Kontrak</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Judul Pekerjaan</td>
						<td>
							<div>
								<!-- Textfield judul pekerjaan -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Deskripsi Pekerjaan</td>
						<td>
							<div>
								<!-- Textarea deksripsi pekerjaan -->
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<!-- End Contract Header -->
		<!-- Start Contract Item -->
		<div class="box">
			<div class="title">
				ITEM
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1" id="contractItem">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 150px;">Kode Barang / Jasa</th>
							<th>Deskripsi</th>
							<th style="width: 200px;">Harga Satuan</th>
							<th style="width: 100px;">Satuan</th>
							<th style="width: 100px;">Jumlah</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Contract Item -->
		<!-- Start Contract Milestone -->
		<div class="box">
			<div class="title">
				MILESTONE
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1" id="contractMilestone">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th>Deskripsi</th>
							<th style="width: 200px;">Tanggal Target</th>
							<th style="width: 100px;">Bobot</th>
							<th style="width: 75px;"></th>
							<th style="width: 75px;"></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><input type="button" class="uibutton" value="Ubah" /></td>
							<td style="text-align: center;"><input type="button" class="uibutton" value="Hapus" /></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Contract Milestone -->
		<!-- Start Contract Lampiran -->
		<div class="box">
			<div class="title">
				LAMPIRAN
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1" id="contractAttachment">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 200px;">Kategori</th>
							<th>Deskripsi Lampiran</th>
							<th style="width: 300px;">File</th>
							<th style="width: 75px;">Kirim Ke Vendor</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><input type="checkbox" /></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Contract Lampiran -->
		
		<!-- Start Contract Comment -->
		<div class="box">
			<div class="title">
				KOMENTAR
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;">Komentar Anda</td>
						<td>
							<div>
								<!-- Textarea komentar -->
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<!-- End Contract Comment -->
		
		<!-- Start Button Container -->
		<div class="box">
			<div class="uibutton-toolbar">
				<input type="submit" value="Simpan Sementara" class="uibutton" />
				<input type="submit" value="Simpan" class="uibutton" />
				<input type="submit" value="Kembali" class="uibutton">
			</div>
		</div>
		<!-- End Button Container -->
	</div>
</div>