<?php

namespace DoctrineORMModule\Proxy\__CG__\Vendor\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vendor extends \Vendor\Entity\Vendor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'kode', 'nama', 'kodeLogin', 'password', 'alamatEmail', 'awalan', 'awalanLain', 'akhiran', 'akhiranLain', 'alamat', 'kota', 'propinsi', 'kodePos', 'negara', 'nomorTelepon', 'website', 'nomorDomisili', 'tanggalDomisili', 'kadaluarsaDomisili', 'namaKontak', 'jabatanKontak', 'nomorTeleponKontak', 'emailKontak', 'npp', 'tanggalNpp', 'nomorNpwp', 'alamatNpwp', 'kotaNpwp', 'propinsiNpwp', 'kodePosNpwp', 'pkpNpwp', 'nomorPkpNpwp', 'tipeVendor', 'tipeSiupIujk', 'siupDiterbitkanOleh', 'nomorSiup', 'tipeSiup', 'dariTanggalSiup', 'sampaiTanggalSiup', 'tdpDiterbitkanOleh', 'nomorTdp', 'dariTglTdp', 'sampaiTglTdp', 'agenPenerbit', 'dariAgen', 'hinggaAgen', 'penerbitImp', 'dariImp', 'keImp', 'attOrg', 'mataUangModalDasar', 'modalDasar', 'mataUangModalSetor', 'modalSetor', 'mataUangAssetdasar', 'assetDasar', 'mataUangLaporanKeu', 'tahunLaporanKeu', 'typeLaporanKeu', 'assetLaporanKeu', 'hutangLaporanKeu', 'pendapatanLaporanKeu', 'labaLaporanKeu', 'golonganKeuangan', 'berakhirDari', 'berakhirSampai', 'diakhiriOleh', 'status', 'halamanSelanjutnya', 'kodeStatusReg', 'statusReg', 'sessionIdReg', 'nomorVendor', 'kodeVendorHu', 'tanggalRekam', 'petugasRekam', 'tanggalUbah', 'petugasUbah');
        }

        return array('__isInitialized__', 'kode', 'nama', 'kodeLogin', 'password', 'alamatEmail', 'awalan', 'awalanLain', 'akhiran', 'akhiranLain', 'alamat', 'kota', 'propinsi', 'kodePos', 'negara', 'nomorTelepon', 'website', 'nomorDomisili', 'tanggalDomisili', 'kadaluarsaDomisili', 'namaKontak', 'jabatanKontak', 'nomorTeleponKontak', 'emailKontak', 'npp', 'tanggalNpp', 'nomorNpwp', 'alamatNpwp', 'kotaNpwp', 'propinsiNpwp', 'kodePosNpwp', 'pkpNpwp', 'nomorPkpNpwp', 'tipeVendor', 'tipeSiupIujk', 'siupDiterbitkanOleh', 'nomorSiup', 'tipeSiup', 'dariTanggalSiup', 'sampaiTanggalSiup', 'tdpDiterbitkanOleh', 'nomorTdp', 'dariTglTdp', 'sampaiTglTdp', 'agenPenerbit', 'dariAgen', 'hinggaAgen', 'penerbitImp', 'dariImp', 'keImp', 'attOrg', 'mataUangModalDasar', 'modalDasar', 'mataUangModalSetor', 'modalSetor', 'mataUangAssetdasar', 'assetDasar', 'mataUangLaporanKeu', 'tahunLaporanKeu', 'typeLaporanKeu', 'assetLaporanKeu', 'hutangLaporanKeu', 'pendapatanLaporanKeu', 'labaLaporanKeu', 'golonganKeuangan', 'berakhirDari', 'berakhirSampai', 'diakhiriOleh', 'status', 'halamanSelanjutnya', 'kodeStatusReg', 'statusReg', 'sessionIdReg', 'nomorVendor', 'kodeVendorHu', 'tanggalRekam', 'petugasRekam', 'tanggalUbah', 'petugasUbah');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vendor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getKode()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getKode();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKode', array());

        return parent::getKode();
    }

    /**
     * {@inheritDoc}
     */
    public function setKode($kode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKode', array($kode));

        return parent::setKode($kode);
    }

    /**
     * {@inheritDoc}
     */
    public function getNama()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNama', array());

        return parent::getNama();
    }

    /**
     * {@inheritDoc}
     */
    public function setNama($nama)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNama', array($nama));

        return parent::setNama($nama);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeLogin', array());

        return parent::getKodeLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeLogin($kodeLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeLogin', array($kodeLogin));

        return parent::setKodeLogin($kodeLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlamatEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlamatEmail', array());

        return parent::getAlamatEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlamatEmail($alamatEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlamatEmail', array($alamatEmail));

        return parent::setAlamatEmail($alamatEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAwalan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAwalan', array());

        return parent::getAwalan();
    }

    /**
     * {@inheritDoc}
     */
    public function setAwalan($awalan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAwalan', array($awalan));

        return parent::setAwalan($awalan);
    }

    /**
     * {@inheritDoc}
     */
    public function getAwalanLain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAwalanLain', array());

        return parent::getAwalanLain();
    }

    /**
     * {@inheritDoc}
     */
    public function setAwalanLain($awalanLain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAwalanLain', array($awalanLain));

        return parent::setAwalanLain($awalanLain);
    }

    /**
     * {@inheritDoc}
     */
    public function getAkhiran()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAkhiran', array());

        return parent::getAkhiran();
    }

    /**
     * {@inheritDoc}
     */
    public function setAkhiran($akhiran)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAkhiran', array($akhiran));

        return parent::setAkhiran($akhiran);
    }

    /**
     * {@inheritDoc}
     */
    public function getAkhiranLain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAkhiranLain', array());

        return parent::getAkhiranLain();
    }

    /**
     * {@inheritDoc}
     */
    public function setAkhiranLain($akhiranLain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAkhiranLain', array($akhiranLain));

        return parent::setAkhiranLain($akhiranLain);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlamat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlamat', array());

        return parent::getAlamat();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlamat($alamat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlamat', array($alamat));

        return parent::setAlamat($alamat);
    }

    /**
     * {@inheritDoc}
     */
    public function getKota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKota', array());

        return parent::getKota();
    }

    /**
     * {@inheritDoc}
     */
    public function setKota($kota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKota', array($kota));

        return parent::setKota($kota);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropinsi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropinsi', array());

        return parent::getPropinsi();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropinsi($propinsi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropinsi', array($propinsi));

        return parent::setPropinsi($propinsi);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodePos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodePos', array());

        return parent::getKodePos();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodePos($kodePos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodePos', array($kodePos));

        return parent::setKodePos($kodePos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegara()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegara', array());

        return parent::getNegara();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegara($negara)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegara', array($negara));

        return parent::setNegara($negara);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorTelepon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorTelepon', array());

        return parent::getNomorTelepon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorTelepon($nomorTelapon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorTelepon', array($nomorTelapon));

        return parent::setNomorTelepon($nomorTelapon);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorDomisili()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorDomisili', array());

        return parent::getNomorDomisili();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorDomisili($nomorDomisili)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorDomisili', array($nomorDomisili));

        return parent::setNomorDomisili($nomorDomisili);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalDomisili()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalDomisili', array());

        return parent::getTanggalDomisili();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalDomisli($tanggalDomisili)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalDomisli', array($tanggalDomisili));

        return parent::setTanggalDomisli($tanggalDomisili);
    }

    /**
     * {@inheritDoc}
     */
    public function getKadaluarsaDomisili()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKadaluarsaDomisili', array());

        return parent::getKadaluarsaDomisili();
    }

    /**
     * {@inheritDoc}
     */
    public function setKadaluarsaDomisili($kadaluarsaDomisili)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKadaluarsaDomisili', array($kadaluarsaDomisili));

        return parent::setKadaluarsaDomisili($kadaluarsaDomisili);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaKontak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaKontak', array());

        return parent::getNamaKontak();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaKontak($namaKontak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaKontak', array($namaKontak));

        return parent::setNamaKontak($namaKontak);
    }

    /**
     * {@inheritDoc}
     */
    public function getJabatanKontak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJabatanKontak', array());

        return parent::getJabatanKontak();
    }

    /**
     * {@inheritDoc}
     */
    public function setJabatanKontak($jabatanKontak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJabatanKontak', array($jabatanKontak));

        return parent::setJabatanKontak($jabatanKontak);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorTeleponKontak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorTeleponKontak', array());

        return parent::getNomorTeleponKontak();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorTeleponKontak($nomorTeleponKontak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorTeleponKontak', array($nomorTeleponKontak));

        return parent::setNomorTeleponKontak($nomorTeleponKontak);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailKontak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailKontak', array());

        return parent::getEmailKontak();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailKontak($emailKontak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailKontak', array($emailKontak));

        return parent::setEmailKontak($emailKontak);
    }

    /**
     * {@inheritDoc}
     */
    public function getNpp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNpp', array());

        return parent::getNpp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNpp($npp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNpp', array($npp));

        return parent::setNpp($npp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalNpp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalNpp', array());

        return parent::getTanggalNpp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalNpp($tanggalNpp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalNpp', array($tanggalNpp));

        return parent::setTanggalNpp($tanggalNpp);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorNpwp', array());

        return parent::getNomorNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorNpwp($nomorNpwp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorNpwp', array($nomorNpwp));

        return parent::setNomorNpwp($nomorNpwp);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlamatNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlamatNpwp', array());

        return parent::getAlamatNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlamatNpwp($alamatNpwp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlamatNpwp', array($alamatNpwp));

        return parent::setAlamatNpwp($alamatNpwp);
    }

    /**
     * {@inheritDoc}
     */
    public function getKotaNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKotaNpwp', array());

        return parent::getKotaNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function setKotaNpwp($kotaNpwp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKotaNpwp', array($kotaNpwp));

        return parent::setKotaNpwp($kotaNpwp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropinsiNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropinsiNpwp', array());

        return parent::getPropinsiNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function getKodePosNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodePosNpwp', array());

        return parent::getKodePosNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodePosNpwp($kodePosNpwp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodePosNpwp', array($kodePosNpwp));

        return parent::setKodePosNpwp($kodePosNpwp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPkpNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkpNpwp', array());

        return parent::getPkpNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPkpNpwp($pkpNpwp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPkpNpwp', array($pkpNpwp));

        return parent::setPkpNpwp($pkpNpwp);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorPkpNpwp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorPkpNpwp', array());

        return parent::getNomorPkpNpwp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorPkpNpwp($nomorPkpNpwp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorPkpNpwp', array($nomorPkpNpwp));

        return parent::setNomorPkpNpwp($nomorPkpNpwp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipeVendor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipeVendor', array());

        return parent::getTipeVendor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipeVendor($tipeVendor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipeVendor', array($tipeVendor));

        return parent::setTipeVendor($tipeVendor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipeSiupIujk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipeSiupIujk', array());

        return parent::getTipeSiupIujk();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipeSiupIujk($tipeSiupIujk)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipeSiupIujk', array($tipeSiupIujk));

        return parent::setTipeSiupIujk($tipeSiupIujk);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiupDiterbitkanOleh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiupDiterbitkanOleh', array());

        return parent::getSiupDiterbitkanOleh();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiupDiterbitkanOleh($siupDiterbitkanOleh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiupDiterbitkanOleh', array($siupDiterbitkanOleh));

        return parent::setSiupDiterbitkanOleh($siupDiterbitkanOleh);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorSiup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorSiup', array());

        return parent::getNomorSiup();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorSiup($nomorSiup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorSiup', array($nomorSiup));

        return parent::setNomorSiup($nomorSiup);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipeSiup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipeSiup', array());

        return parent::getTipeSiup();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipeSiup($tipeSiup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipeSiup', array($tipeSiup));

        return parent::setTipeSiup($tipeSiup);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorVendor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorVendor', array());

        return parent::getNomorVendor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorVendor($nomorVendor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorVendor', array($nomorVendor));

        return parent::setNomorVendor($nomorVendor);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeVendorHu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeVendorHu', array());

        return parent::getKodeVendorHu();
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalRekam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalRekam', array());

        return parent::getTanggalRekam();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalRekam($tanggalRekam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalRekam', array($tanggalRekam));

        return parent::setTanggalRekam($tanggalRekam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetugasRekam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetugasRekam', array());

        return parent::getPetugasRekam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetugasRekam($petugasRekam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetugasRekam', array($petugasRekam));

        return parent::setPetugasRekam($petugasRekam);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalUbah()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalUbah', array());

        return parent::getTanggalUbah();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalUbah($tanggalUbah)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalUbah', array($tanggalUbah));

        return parent::setTanggalUbah($tanggalUbah);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetugasUbah()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetugasUbah', array());

        return parent::getPetugasUbah();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetugasUbah($petugasUbah)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetugasUbah', array($petugasUbah));

        return parent::setPetugasUbah($petugasUbah);
    }

}
