<?php

namespace DoctrineORMModule\Proxy\__CG__\Procurement\Entity\Tender;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tender extends \Procurement\Entity\Tender\Tender implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'kode', 'kantor', 'listTenderVendor', 'listKontrak', 'items', 'kodeTenderSebelum', 'kodeTenderSesudah', 'kodePemohon', 'namaPemohon', 'kodeJabatanPemohon', 'kodePerencana', 'namaPerencana', 'kodeJabatanPerencana', 'kodePelaksana', 'namaPelaksana', 'kodeJabatanPelaksana', 'tanggalPembutan', 'judulPekerjaan', 'lingkupPekerjaan', 'waktuPengiriman', 'unitPengiriman', 'namaPembeli', 'kodeJabatanPembeli', 'mataUang', 'tipeKontrak', 'namaJabatanPeserta', 'kodeJabatanPeserta', 'pembutanKontrak', 'status', 'tanggalSelesai', 'kodePerencanaan', 'kodeKantorPerencanaan', 'tanggalRekam', 'petugasRekam', 'tanggalUbah', 'petugasUbah', 'kodeKantorKirim', 'statusManual', 'kegiatanId');
        }

        return array('__isInitialized__', 'kode', 'kantor', 'listTenderVendor', 'listKontrak', 'items', 'kodeTenderSebelum', 'kodeTenderSesudah', 'kodePemohon', 'namaPemohon', 'kodeJabatanPemohon', 'kodePerencana', 'namaPerencana', 'kodeJabatanPerencana', 'kodePelaksana', 'namaPelaksana', 'kodeJabatanPelaksana', 'tanggalPembutan', 'judulPekerjaan', 'lingkupPekerjaan', 'waktuPengiriman', 'unitPengiriman', 'namaPembeli', 'kodeJabatanPembeli', 'mataUang', 'tipeKontrak', 'namaJabatanPeserta', 'kodeJabatanPeserta', 'pembutanKontrak', 'status', 'tanggalSelesai', 'kodePerencanaan', 'kodeKantorPerencanaan', 'tanggalRekam', 'petugasRekam', 'tanggalUbah', 'petugasUbah', 'kodeKantorKirim', 'statusManual', 'kegiatanId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tender $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getKode()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getKode();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKode', array());

        return parent::getKode();
    }

    /**
     * {@inheritDoc}
     */
    public function setKode($kode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKode', array($kode));

        return parent::setKode($kode);
    }

    /**
     * {@inheritDoc}
     */
    public function getKantor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKantor', array());

        return parent::getKantor();
    }

    /**
     * {@inheritDoc}
     */
    public function setKantor(\Application\Entity\Kantor $kantor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKantor', array($kantor));

        return parent::setKantor($kantor);
    }

    /**
     * {@inheritDoc}
     */
    public function getListTenderVendor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListTenderVendor', array());

        return parent::getListTenderVendor();
    }

    /**
     * {@inheritDoc}
     */
    public function setListTenderVendor($listTenderVendor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListTenderVendor', array($listTenderVendor));

        return parent::setListTenderVendor($listTenderVendor);
    }

    /**
     * {@inheritDoc}
     */
    public function getListKontrak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListKontrak', array());

        return parent::getListKontrak();
    }

    /**
     * {@inheritDoc}
     */
    public function setListKontrak($listKontrak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListKontrak', array($listKontrak));

        return parent::setListKontrak($listKontrak);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', array());

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setItems(\Doctrine\Common\Collections\ArrayCollection $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItems', array($items));

        return parent::setItems($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeTenderSebelum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeTenderSebelum', array());

        return parent::getKodeTenderSebelum();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeTenderSebelum($kodeTenderSebelum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeTenderSebelum', array($kodeTenderSebelum));

        return parent::setKodeTenderSebelum($kodeTenderSebelum);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeTenderSesudah()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeTenderSesudah', array());

        return parent::getKodeTenderSesudah();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeTenderSesudah($kodeTenderSesudah)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeTenderSesudah', array($kodeTenderSesudah));

        return parent::setKodeTenderSesudah($kodeTenderSesudah);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodePemohon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodePemohon', array());

        return parent::getKodePemohon();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodePemohon($kodePemohon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodePemohon', array($kodePemohon));

        return parent::setKodePemohon($kodePemohon);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaPemohon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaPemohon', array());

        return parent::getNamaPemohon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaPemohon($namaPemohon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaPemohon', array($namaPemohon));

        return parent::setNamaPemohon($namaPemohon);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeJabatanPemohon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeJabatanPemohon', array());

        return parent::getKodeJabatanPemohon();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeJabatanPemohon($kodeJabatanPemohon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeJabatanPemohon', array($kodeJabatanPemohon));

        return parent::setKodeJabatanPemohon($kodeJabatanPemohon);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodePerencana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodePerencana', array());

        return parent::getKodePerencana();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodePerencana($kodePerencana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodePerencana', array($kodePerencana));

        return parent::setKodePerencana($kodePerencana);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaPerencana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaPerencana', array());

        return parent::getNamaPerencana();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaPerencana($namaPerencana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaPerencana', array($namaPerencana));

        return parent::setNamaPerencana($namaPerencana);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeJabatanPerencana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeJabatanPerencana', array());

        return parent::getKodeJabatanPerencana();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeJabatanPerencana($kodeJabatanPerencana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeJabatanPerencana', array($kodeJabatanPerencana));

        return parent::setKodeJabatanPerencana($kodeJabatanPerencana);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodePelaksana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodePelaksana', array());

        return parent::getKodePelaksana();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodePelaksana($kodePelaksana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodePelaksana', array($kodePelaksana));

        return parent::setKodePelaksana($kodePelaksana);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaPelaksana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaPelaksana', array());

        return parent::getNamaPelaksana();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaPelaksana($namaPelaksana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaPelaksana', array($namaPelaksana));

        return parent::setNamaPelaksana($namaPelaksana);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeJabatanPelaksana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeJabatanPelaksana', array());

        return parent::getKodeJabatanPelaksana();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeJabatanPelaksana($kodeJabatanPelaksana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeJabatanPelaksana', array($kodeJabatanPelaksana));

        return parent::setKodeJabatanPelaksana($kodeJabatanPelaksana);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalPembuatan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalPembuatan', array());

        return parent::getTanggalPembuatan();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalPembuatan($tanggalPembuatan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalPembuatan', array($tanggalPembuatan));

        return parent::setTanggalPembuatan($tanggalPembuatan);
    }

    /**
     * {@inheritDoc}
     */
    public function getJudulPekerjaan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJudulPekerjaan', array());

        return parent::getJudulPekerjaan();
    }

    /**
     * {@inheritDoc}
     */
    public function setJudulPekerjaan($juduPekerjaan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJudulPekerjaan', array($juduPekerjaan));

        return parent::setJudulPekerjaan($juduPekerjaan);
    }

    /**
     * {@inheritDoc}
     */
    public function getLingkupPekerjaan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLingkupPekerjaan', array());

        return parent::getLingkupPekerjaan();
    }

    /**
     * {@inheritDoc}
     */
    public function setLingkupPekerjaan($lingkupPekerjaan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLingkupPekerjaan', array($lingkupPekerjaan));

        return parent::setLingkupPekerjaan($lingkupPekerjaan);
    }

    /**
     * {@inheritDoc}
     */
    public function getWaktuPengiriman()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWaktuPengiriman', array());

        return parent::getWaktuPengiriman();
    }

    /**
     * {@inheritDoc}
     */
    public function setWaktuPengiriman($waktuPengiriman)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWaktuPengiriman', array($waktuPengiriman));

        return parent::setWaktuPengiriman($waktuPengiriman);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitPengiriman()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitPengiriman', array());

        return parent::getUnitPengiriman();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnitPengiriman($unitPengiriman)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitPengiriman', array($unitPengiriman));

        return parent::setUnitPengiriman($unitPengiriman);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaPembeli()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaPembeli', array());

        return parent::getNamaPembeli();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaPembeli($namaPembeli)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaPembeli', array($namaPembeli));

        return parent::setNamaPembeli($namaPembeli);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeJabatanPembeli()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeJabatanPembeli', array());

        return parent::getKodeJabatanPembeli();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeJabatanPembeli($kodeJabatanPembeli)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeJabatanPembeli', array($kodeJabatanPembeli));

        return parent::setKodeJabatanPembeli($kodeJabatanPembeli);
    }

    /**
     * {@inheritDoc}
     */
    public function getMataUang()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMataUang', array());

        return parent::getMataUang();
    }

    /**
     * {@inheritDoc}
     */
    public function setMataUang($mataUang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMataUang', array($mataUang));

        return parent::setMataUang($mataUang);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipeKontrak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipeKontrak', array());

        return parent::getTipeKontrak();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipeKontrak($tipeKontrak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipeKontrak', array($tipeKontrak));

        return parent::setTipeKontrak($tipeKontrak);
    }

    /**
     * {@inheritDoc}
     */
    public function getNamaJabatanPeserta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamaJabatanPeserta', array());

        return parent::getNamaJabatanPeserta();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamaJabatanPeserta($namaJabatanPeserta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamaJabatanPeserta', array($namaJabatanPeserta));

        return parent::setNamaJabatanPeserta($namaJabatanPeserta);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeJabatanPeserta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeJabatanPeserta', array());

        return parent::getKodeJabatanPeserta();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeJabatanPeserta($kodeJabatanPeserta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeJabatanPeserta', array($kodeJabatanPeserta));

        return parent::setKodeJabatanPeserta($kodeJabatanPeserta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPembutanKontrak()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPembutanKontrak', array());

        return parent::getPembutanKontrak();
    }

    /**
     * {@inheritDoc}
     */
    public function setPembutanKontrak($pembutanKontrak)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPembutanKontrak', array($pembutanKontrak));

        return parent::setPembutanKontrak($pembutanKontrak);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalSelesai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalSelesai', array());

        return parent::getTanggalSelesai();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalSelesai($tanggalSelesai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalSelesai', array($tanggalSelesai));

        return parent::setTanggalSelesai($tanggalSelesai);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodePerencanaan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodePerencanaan', array());

        return parent::getKodePerencanaan();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodePerencanaan($kodePerencanaan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodePerencanaan', array($kodePerencanaan));

        return parent::setKodePerencanaan($kodePerencanaan);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeKantorPerencanaan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeKantorPerencanaan', array());

        return parent::getKodeKantorPerencanaan();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeKantorPerencanaan($kodeKantorPerencanaan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeKantorPerencanaan', array($kodeKantorPerencanaan));

        return parent::setKodeKantorPerencanaan($kodeKantorPerencanaan);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalRekam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalRekam', array());

        return parent::getTanggalRekam();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalRekam($tanggalRekam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalRekam', array($tanggalRekam));

        return parent::setTanggalRekam($tanggalRekam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetugasRekam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetugasRekam', array());

        return parent::getPetugasRekam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetugasRekam($petugasRekam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetugasRekam', array($petugasRekam));

        return parent::setPetugasRekam($petugasRekam);
    }

    /**
     * {@inheritDoc}
     */
    public function getTanggalUbah()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTanggalUbah', array());

        return parent::getTanggalUbah();
    }

    /**
     * {@inheritDoc}
     */
    public function setTanggalUbah($tanggalUbah)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTanggalUbah', array($tanggalUbah));

        return parent::setTanggalUbah($tanggalUbah);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetugasUbah()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetugasUbah', array());

        return parent::getPetugasUbah();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetugasUbah($petugasUbah)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetugasUbah', array($petugasUbah));

        return parent::setPetugasUbah($petugasUbah);
    }

    /**
     * {@inheritDoc}
     */
    public function getKodeKantorKirim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKodeKantorKirim', array());

        return parent::getKodeKantorKirim();
    }

    /**
     * {@inheritDoc}
     */
    public function setKodeKantorKirim($kodeKantorKirim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKodeKantorKirim', array($kodeKantorKirim));

        return parent::setKodeKantorKirim($kodeKantorKirim);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusManual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusManual', array());

        return parent::getStatusManual();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusManual($statusManual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusManual', array($statusManual));

        return parent::setStatusManual($statusManual);
    }

    /**
     * {@inheritDoc}
     */
    public function getKegiatanId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKegiatanId', array());

        return parent::getKegiatanId();
    }

    /**
     * {@inheritDoc}
     */
    public function setKegiatanId($kegiatanId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKegiatanId', array($kegiatanId));

        return parent::setKegiatanId($kegiatanId);
    }

}
