<?php
$title = 'Login Form';
$this->headTitle($title);
?>
<div id="right">
	<div class="section">
		<!-- Start Contract Header -->
		<div class="box">
			<div class="title">
				LOGIN
				<span class="hide"></span>
			</div>
			<div class="content">
				<?php
				$form = $this->loginForm;
				$form->prepare();
				
				echo $this->form()->openTag($form);
				echo $this->formElementErrors($form);
				echo $this->formRow($form->get('username'));
				echo $this->formRow($form->get('password'));
				echo $this->formRow($form->get('security'));
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
				?>
			</div>
		</div>
	</div>
</div>