<div id="right">
	<div class="section">
		<!-- Start Work Order Header -->
		<div class="box">
			<div class="title">
				HEADER WORK ORDER
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;">Nomor Work Order</td>
						<td>
							<div>(Generate Automatis)</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Nomor Kontrak</td>
						<td>
							<div>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Nama Pembuat</td>
						<td>
							<div>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Vendor</td>
						<td>
							<div>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tanggal Mulai</td>
						<td>
							<div>
								<!-- Datepicket tanggal mulai -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Tanggal Berakhir</td>
						<td>
							<div>
								<!-- Datepicker tanggal berakhir -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Deskripsi</td>
						<td>
							<div>
								<!-- Textarea deskripsi WO -->
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Total Nilai Kontrak</td>
						<td>
							<div>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Total Sudah Dikeluarkan</td>
						<td>
							<div>
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Sisa Nilai Kontrak</td>
						<td>
							<div>
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<!-- End Work Order Header -->
		<!-- Start Work Order Item -->
		<div class="box">
			<div class="title">
				ITEM WORK ORDER
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1" id="contractItem">
					<thead>
						<tr>
							<th style="width: 75px;">Pilih</th>
							<th style="width: 150px;">Kode Barang / Jasa</th>
							<th>Deskripsi</th>
							<th style="width: 150px;">Harga Satuan</th>
							<th style="width: 100px;">Jumlah Order Minimum</th>
							<th style="width: 100px;">Jumlah Order Maximum</th>
							<th style="width: 100px;">Jumlah Order</th>
							<th style="width: 100px;">Satuan</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center;"><input type="checkbox" /></td>
							<td style="text-align: center;"></td>
							<td style="text-align: left;"></td>
							<td style="text-align: right;"></td>
							<td style="text-align: center;"></td>
							<td style="text-align: center;"></td>
							<td style="text-align: center;"></td>
							<td style="text-align: center;"></td>
						</tr>
					</tbody>
					<thead>
						<tr>
							<th colspan="6" style="text-align: right;">TOTAL NILAI WO</th>
							<th colspan="2" style="text-align: right;"></th>
						</tr>
						<tr>
							<th colspan="6" style="text-align: right;">PPN (10%)</th>
							<th colspan="2" style="text-align: right;"></th>
						</tr>
						<tr>
							<th colspan="6" style="text-align: right;">TOTAL NILAI WO SETELAH PPN</th>
							<th colspan="2" style="text-align: right;"></th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
		<!-- End Work Order Item -->
		<!-- Start Work Order Comment -->
		<div class="box">
			<div class="title">
				KOMENTAR
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;">Komentar Anda</td>
						<td>
							<div>
								<!-- Textarea komentar -->
							</div>
						</td>
					</tr>
				</table>
			</div>
		</div>
		<!-- End Work Order Comment -->
		<!-- Start Button Container -->
		<div class="box">
			<div class="content" style="text-align: center">
				<input type="submit" value="Kirim" class="uibutton" />
				<input type="submit" value="Kembali" class="uibutton">
			</div>
		</div>
		<!-- End Button Container -->
	</div>
</div>