<div id="right">
	<div class="section">
		<div class="box">
			<div class="title">
				KONTRAK HARGA SATUAN
				<span class="hide"></span>
			</div>
			<div class="content">
				<!-- Start Contract Filter -->
				<table class="form formStyle2">
					<tr>
						<td class="head" style="width: 200px;">Cari Berdasarkan</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">Status Kontrak</td>
						<td>
							<div>
								
							</div>
						</td>
					</tr>
					<tr>
						<td class="head" style="width: 200px;">&nbsp;</td>
						<td>
							<div>
								<input type="submit" value="Filter" class="uibutton" />
								<input type="reset" value="Reset" class="uibutton" />
							</div>
						</td>
					</tr>
				</table>
				<!-- End Contract Filter -->
				
				<!-- Start Contract List -->
				<table class="style1 all" id="satuanContract">
					<thead>
						<tr>
							<th style="width:50px;">No</th>
							<th style="width:150px;">Nomor Pengadaan</th>
							<th style="width:150px;">Nomor Kontrak</th>
							<th>Deskripsi Pekerjaan</th>
							<th style="width:150px;">Tipe Kontrak</th>
							<th style="width:200px;">Vendor</th>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
				<!-- Start Contract List -->
			</div>
		</div>
	</div>
</div>