<div id="right">
	<div class="section">
		<div class="box">
			<div class="title">
				Riwayat Cetak Laporan
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="reportHistory">
					<thead>
						<tr>
							<th>Nama Report</th>
							<th style="width:150px;">Petugas</th>
							<th style="width:150px;">Unit Kerja</th>
							<th style="width:75px;">Dibagikan</th>
							<th style="width:75px;">File</th>
							<th style="width:150px;">Tanggal Cetak</th>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>