<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
		
		<?php echo $this->headMeta()
	            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
	            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	    ?>
	    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
		
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
			->prependStylesheet($this->basePath() . '/css/base.css')
			->prependStylesheet($this->basePath() . '/css/style.css')
		?>
				
		
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/bootstrap.min.js', 'text/javascript')
			
			->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
			
			/**
			 * Script berikut ini dari layout ryan.
			 */
			->prependFile($this->basePath() . '/js/jquery-2.0.2.min.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js', 'text/javascript')
			
			// Untuk kepentingan form
			->prependFile($this->basePath() . '/js/jquery.form.js', 'text/javascript')
			
			// Untuk kepentingan form validation
			->prependFile($this->basePath() . '/js/jquery.validate.min.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jquery.validate-id.js', 'text/javascript')
			
			->prependFile($this->basePath() . '/js/jquery.elastic.source.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jquery.placeholder.min.js', 'text/javascript')
			
			// Untuk kepentingan breadcrumb
			->prependFile($this->basePath() . '/js/jquery.easing.1.3.js', 'text/javascript')
			->prependFile($this->basePath() . '/js/jquery.jBreadCrumb.1.1.js', 'text/javascript')
			
			// Untuk kepentingan browser.
			->prependFile($this->basePath() . '/js/jquery.browser.js', 'text/javascript')
        ?>
		
		<script type="text/javascript">
	    	jQuery(document).ready(function(){
	    		jQuery(".breadCrumb").jBreadCrumb();

	    		var top = $('nav').offset().top - parseFloat($('nav').css('marginTop').replace(/auto/, 0));
    			$(window).scroll(function (event) {
    				// what the y position of the scroll is
    			    var y = $(this).scrollTop();
    			  
    			    // whether that's below the form
    			    if (y >= top) {
    			    	// if so, ad the fixed class
    			    	$('nav').addClass('fixedNavigation');
    			    }else {
    			    	// otherwise remove it
    			    	$('nav').removeClass('fixedNavigation');
    			    }
    			});
	        });
	    </script>
	    
	    <!--[if IE]>
		<script type="text/javascript">
			$.ajaxSetup({ cache: false });
		</script>
		<![endif]-->
	</head>
	<body>
		<div class="topbar"> 
		    <div class="content" style="font-size: 9pt;">
		    	
		    </div>  
		</div>
		<div class="clear"></div>
		
		<div class="header">
			<div class="headerLogo">
			</div>
		</div>
		
		<!-- Main Menu -->
		<nav>
			<ul>
				<li><a href="#" id="m1">Dashboard</a></li>
				<li class="sub"><a href="#">Administrasi</a>
					<ul>
						<li class="sub"><a href="#">Security</a>
							<ul>
								<li><a href="#">Data Pengguna</a></li>
							</ul>
						</li>
						<li class="sub"><a href="#">Pengaturan Risiko</a>
							<ul>
								<li><a href="#">Grup Selera</a></li>
							</ul>
						</li>
						<li><a href="#">Persetujuan Bertingkat</a></li>
					</ul>
				</li>
				<li class="sub"><a href="#">Pustaka</a>
					<ul>
						<li class="sub"><a href="#">Data Pustaka</a>
							<ul>
								<li><a href="#">Pustaka Sasaran</a></li>
								<li><a href="#">Pustaka Proses</a></li>
								
								<li><a href="#">Pustaka Kategori Detil Proses</a></li>
								<li><a href="#">Pustaka Detil Proses</a></li>
							</ul>
						</li>
						<li class="sub"><a href="#">Pemetaan</a>
							<ul>
								<li><a href="#">Proses - Detil Proses</a></li>
								<li><a href="#">Detil Proses - Potensi Risiko</a></li>
								<li><a href="#">Detil Proses - Penanganan</a></li>
								<li><a href="#">Potensi Risiko - Penanganan</a></li>
								<li><a href="#">Potensi Risiko - Penyebab</a></li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</nav>
		<!-- End of Main Menu -->
		
		<div id="wrapper">
			<div id="container">
				<!-- Start Content -->			
				<?php echo $this->content; ?>
				<!-- End Content -->
			</div>
		</div> 
		
		<div class="clear"></div>
		<footer>
			<p>eProc Jamsostek<br />Copyright &copy; 2013</p>
		</footer>
		<?php echo $this->inlineScript() ?>
	</body>
</html>