<?php 
use Contract\Todo\ContractCreateTodoItem;
use Application\Entity\Role;
?>
<div id="right">
	<div class="section">
		<!-- Start Initiation Todo -->
		<?php if($this->identity()->getActiveRole()->getKode() === Role::KODE_APPROVAL_KONTRAK_DAN_VENDOR) : ?>
		<div class="box">
			<div class="title">
				DAFTAR HASIL PENGADAAN UNTUK DIBUAT KONTRAK
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="initiateTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 125px;">Nomor Pengadaan</th>
							<th>Deskripsi Pekerjaan</th>
							<th style="width: 200px;">Lingkup Pekerjaan</th>
							<th style="width: 150px;">Vendor</th>
							<th style="width: 125px;">Tanggal Penetapan</th>
							<th style="width: 75px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
					<?php 
						$index = 1;
						/* @var $initTodoItem Contract\Todo\ContractInitTodoItem */ 
						foreach ($this->initTodoListProvider->getListData(1, 10000) as $initTodoItem) : 
					?>
						<tr>
							<td style="text-align: center;"><?php echo $index ?></td>
							<td style="text-align: center;"><?php echo $initTodoItem->getKodeTender()?></td>
							<td><?php echo $initTodoItem->getJudulPekerjaan()?></td>
							<td><?php echo $initTodoItem->getLingkupPekerjaan()?></td>
							<td><?php echo $initTodoItem->getNamaVendor() ?></td>
							<td style="text-align: center;"><?php echo ($tanggalPenetapan = $initTodoItem->getTanggalPenetapan()) != null ? $tanggalPenetapan->format('d/m/Y') : ''?></td>
							<td style="text-align: center;"><a href="<?php echo $this->url($initTodoItem->getActionRoute(), $initTodoItem->getActionRouteParams())?>" class="uibutton" />Proses</a></td>
						</tr>
					<?php 
						$index++;
						endforeach; 
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php endif; ?>
		<!-- End Initiation Todo -->
		
		<!-- Start Contract Todo -->
		<?php if($this->identity()->getActiveRole()->getKode() === Role::KODE_PELAKSANA_KONTRAK) : ?>
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN PEMBUATAN KONTRAK
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="createTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 125px;">Nomor Pengadaan</th>
							<th>Deskripsi Pekerjaan</th>
							<th style="width: 200px;">Vendor</th>
							<th style="width: 200px;">Status</th>
							<th style="width: 125px;">Tgl Mulai</th>
							<th style="width: 75px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
					<?php 
						$index = 1;
						/* @var $createTodoItem ContractCreateTodoItem */ 
						foreach ($createTodoListProvider->getListData(1, 1000) as $createTodoItem) :
					?>
						<tr>
							<td style="text-align: center;"><?php echo $index ?></td>
							<td style="text-align: center;"><?php echo $createTodoItem->getKodeTender()?></td>
							<td><?php echo $createTodoItem->getJudulPekerjaan()?></td>
							<td><?php echo $createTodoItem->getNamaVendor()?></td>
							<td style="text-align: left;"><?php echo strtoupper($createTodoItem->getStatusProses())?></td>
							<td style="text-align: center;"><?php echo $createTodoItem->getCreatedDate()->format('d/m/Y H:i:s')?></td>
							<td style="text-align: center;"><a href="<?php echo $this->url($createTodoItem->getActionRoute(), $createTodoItem->getActionRouteParams())?>" class="uibutton" />Proses</a></td>
						</tr>
					<?php 
						$index++;
						endforeach;
					?>
					</tbody>
				</table>
			</div>
		</div>
		<?php endif; ?>
		<!-- End Initiation Todo -->
		
		<!-- Start Amend Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN ADENDUM KONTRAK
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="amendTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 125px;">Nomor Kontrak</th>
							<th>Deskripsi Pekerjaan</th>
							<th style="width: 200px;">Vendor</th>
							<th style="width: 200px;">Status</th>
							<th style="width: 125px;">Tgl Mulai</th>
							<th style="width: 75px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center;"></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><a class="uibutton" />Proses</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Amend Todo -->
		
		<!-- Start Work Order Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN WORK ORDER
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="workOrderTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 125px;">Nomor Kontrak</th>
							<th>Deskripsi Work Order</th>
							<th style="width: 200px;">Vendor</th>
							<th style="width: 200px;">Status</th>
							<th style="width: 125px;">Tgl Mulai</th>
							<th style="width: 75px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center;"></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><a class="uibutton" />Proses</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Work Order Todo -->
		
		<!-- Start Progress Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN PROGRESS
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="progresTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 125px;">Nomor Kontrak</th>
							<th>Deskripsi</th>
							<th style="width: 200px;">Vendor</th>
							<th style="width: 100px;">Persentase</th>
							<th style="width: 200px;">Status</th>
							<th style="width: 200px;">Tgl Mulai</th>
							<th style="width: 75px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center;"></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: right;"></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><a class="uibutton" />Proses</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Progress Todo -->
		
		<!-- Start Invoice Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN TAGIHAN
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="invoiceTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 125px;">Nomor Kontrak</th>
							<th style="width: 150px;">Nomor Tagihan</th>
							<th style="width: 200px;">Tanggal Pembuatan</th>
							<th style="width: 200px;">Tanggal Tagihan</th>
							<th>Status</th>
							<th style="width: 75px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td style="text-align: center;"></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align: center;"><a class="uibutton" />Proses</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Invoice Todo -->
	</div>
</div>