<div id="right">
	<div class="section">
		<!-- Start Initiation Todo -->
		<div class="box">
			<div class="title">
				DAFTAR HASIL PENGADAAN UNTUK DIBUAT KONTRAK
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="initiateTodo">
					<thead>
						<tr>
							<th style="width: 50px;">No</th>
							<th style="width: 150px;">Nomor Pengadaan</th>
							<th>Deskripsi Pekerjaan</th>
							<th style="width: 200px;">Vendor</th>
							<th style="width: 200px;">Tanggal Penetapan</th>
							<th style="width: 100px;">Aksi</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Initiation Todo -->
		
		<!-- Start Contract Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN PEMBUATAN KONTRAK
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="createTodo">
					<thead>
						<tr>
							<th>No</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Initiation Todo -->
		
		<!-- Start Amend Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN ADENDUM KONTRAK
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="amendTodo">
					<thead>
						<tr>
							<th>No</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Amend Todo -->
		
		<!-- Start Work Order Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN WORK ORDER
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="workOrderTodo">
					<thead>
						<tr>
							<th>No</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Work Order Todo -->
		
		<!-- Start Progress Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN PROGRESS
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="progresTodo">
					<thead>
						<tr>
							<th>No</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Progress Todo -->
		
		<!-- Start Invoice Todo -->
		<div class="box">
			<div class="title">
				DAFTAR PEKERJAAN TAGIHAN
				<span class="hide"></span>
			</div>
			<div class="content">
				<table class="style1 all" id="invoiceTodo">
					<thead>
						<tr>
							<th>No</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- End Invoice Todo -->
	</div>
</div>